spring.application.name=practiceSpringMVC

countries=Viet Nam,Belgium,France,Germany,Italy,Spain,United Kingdom,United States
programmingLanguages=Go,Java,JavaScript,Python,Ruby,C++
systems=Windows,macOS,Linux,Unix